
parent: PRS01
name: child_PRS01
display_name: Child theme of PRS01's theme
version: 1.0.0
assets:
  use_parent_assets: true
  js:
    all:
      - id: "owl-lib"
        path: "assets/js/owl.carousel.min.js"
        priority: 355
      - id: "jquerymarquee"
        path: "assets/js/jquery.marquee.min.js"
        priority: 356
dependencies:
  modules:
    - ttbrandlogo
