name: Categories product
description: 
enabled_text: false
required_text: false
enabled_link: false
enabled_image: false
css:
  -
    path: views/templates/front/categoriesproduct/css/categoriesproduct.css
    priority: 200
    position: head
    server: local    
